// Template tags: 
// SpritesDefault - Name of output class.
// Default - Name of current group.
// <sprite_name> - Name of each sprite.
// <sprite_hash_name> - Hash name of each sprite.

using Microsoft.Xna.Framework.Content;
using Monofoxe.Engine;
using Monofoxe.Engine.Drawing;
using System.Collections.Generic;

/*
This file has been autogenerated. Don't mess with it.
*/

namespace Resources.Sprites
{
	public static class SpritesDefault
	{
		#region Sprites.
		public static Sprite Clouds;
		public static Sprite Tile;
		public static Sprite FoxBody;
		public static Sprite VillainBody;
		public static Sprite Block;
		public static Sprite MonkeyBody;
		public static Sprite Tree;
		public static Sprite Coin;
		public static Sprite LaserOrb;
		public static Sprite VillainFace;
		public static Sprite FoxFaceSad;
		public static Sprite FoxFace;
		public static Sprite EnemyPaw;
		public static Sprite FoxPaw;
		public static Sprite MonkeyPaw;
		public static Sprite VillainPaw;
		public static Sprite Pawprint;
		public static Sprite MonkeyFace;
		public static Sprite Main;
		public static Sprite TestMap;
		#endregion Sprites.
		
		private static string _groupName = "Default";
		private static ContentManager _content = new ContentManager(GameCntrl.Game.Services);
		
		public static bool Loaded = false;
		
		public static void Load()
		{
			Loaded = true;
			var graphicsPath = GameCntrl.ContentDir + '/' + GameCntrl.GraphicsDir +  '/' + _groupName;
			var sprites = _content.Load<Dictionary<string, Sprite>>(graphicsPath);
			
			#region Sprite constructors.
			
			Clouds = sprites["clouds"];
			Tile = sprites["tile"];
			FoxBody = sprites["FoxBody"];
			VillainBody = sprites["VillainBody"];
			Block = sprites["Block"];
			MonkeyBody = sprites["MonkeyBody"];
			Tree = sprites["tree"];
			Coin = sprites["coin"];
			LaserOrb = sprites["LaserOrb"];
			VillainFace = sprites["VillainFace"];
			FoxFaceSad = sprites["FoxFaceSad"];
			FoxFace = sprites["FoxFace"];
			EnemyPaw = sprites["EnemyPaw"];
			FoxPaw = sprites["FoxPaw"];
			MonkeyPaw = sprites["MonkeyPaw"];
			VillainPaw = sprites["VillainPaw"];
			Pawprint = sprites["pawprint"];
			MonkeyFace = sprites["MonkeyFace"];
			Main = sprites["Maps/Main"];
			TestMap = sprites["Maps/TestMap"];
			
			#endregion Sprite constructors.
		}
		
		public static void Unload()
		{
			_content.Unload();
			Loaded = false;
		}
	}
}
