// Template tags: 
// SpritesDefault - Name of output class.
// Default - Name of current group.
// <sprite_name> - Name of each sprite.
// <sprite_hash_name> - Hash name of each sprite.

using Microsoft.Xna.Framework.Content;
using Monofoxe.Engine;
using Monofoxe.Engine.Drawing;
using System.Collections.Generic;

/*
This file has been autogenerated. Don't mess with it.
*/

namespace Resources.Sprites
{
	public static class SpritesDefault
	{
		#region Sprites.
		public static Sprite Tile;
		public static Sprite FoxBody;
		public static Sprite FoxFace;
		public static Sprite FoxPaw;
		public static Sprite TestMap;
		#endregion Sprites.
		
		private static string _groupName = "Default";
		private static ContentManager _content = new ContentManager(GameCntrl.Game.Services);
		
		public static bool Loaded = false;
		
		public static void Load()
		{
			Loaded = true;
			var graphicsPath = GameCntrl.ContentDir + '/' + GameCntrl.GraphicsDir +  '/' + _groupName;
			var sprites = _content.Load<Dictionary<string, Sprite>>(graphicsPath);
			
			#region Sprite constructors.
			
			Tile = sprites["tile"];
			FoxBody = sprites["FoxBody"];
			FoxFace = sprites["FoxFace"];
			FoxPaw = sprites["FoxPaw"];
			TestMap = sprites["Maps/TestMap"];
			
			#endregion Sprite constructors.
		}
		
		public static void Unload()
		{
			_content.Unload();
			Loaded = false;
		}
	}
}
